# Linear energy neutron point source (20% int) + 16O* replica (80% int)
/gps/source/clear

# Neutron point source
/gps/source/add 0.20
/gps/particle neutron
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
#/gps/ene/type Gauss
#/gps/ene/mono 8.050 MeV
#/gps/ene/sigma 400 keV
/gps/ene/type Lin
/gps/ene/min 0.1 MeV
/gps/ene/max 8.5 MeV
/gps/ene/gradient 0.01
/gps/ene/intercept 1.

# Gamma point sources, 16O*
# 1(1)^- 7115.2
/gps/source/add 0.19175
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 7115.2 keV

# Gamma point sources, 16O*
# 2(1)^+ 6915.6
/gps/source/add 0.19574
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 6915.6 keV

# Gamma point sources, 16O*
# 3(1)^- 6128.6
/gps/source/add 0.21108
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 6128.6 keV

# Gamma point sources, 16O*
# 0(2)^+ 6048.2
/gps/source/add 0.20121
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 6048.2 keV

# Gamma point sources, 16O*
# 1(1)^- 1067.5
/gps/source/add 0.006
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 1067.5 keV

# Gamma point sources, 16O*
# 1(1)^- 986.9
/gps/source/add 0.07
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 986.9 keV

# Gamma point sources, 16O*
# 2(1)^+ 867.7
/gps/source/add 0.027
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 867.7 keV

# Gamma point sources, 16O*
# 2(1)^+ 787.2
/gps/source/add 0.008
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 787.2 keV

# Prints out a table when running
/gps/source/list




