# Linear energy neutron point source (20% int) + 16O* replica (80% int)
/gps/source/clear

# Neutron point source
/gps/source/add 0.49686
/gps/particle neutron
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/ene/type User
/gps/hist/type energy
/gps/hist/point 0. 0.
/gps/hist/point 0.1 0.85
/gps/hist/point 0.5 0.
/gps/hist/point 2.5 0.
/gps/hist/point 2.8 0.1
/gps/hist/point 3. 0.35
/gps/hist/point 3.7 0.9
/gps/hist/point 4.5 1.
/gps/hist/point 4.75 1.2
/gps/hist/point 5. 1.
/gps/hist/point 5.5 0.65
/gps/hist/point 6.5 0.5
/gps/hist/point 7.25 0.

# Gamma point sources, 16O*
# 1(1)^- 7115.2
/gps/source/add 0.12060
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 7115.2 keV

# Gamma point sources, 16O*
# 2(1)^+ 6915.6
/gps/source/add 0.12311
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 6915.6 keV

# Gamma point sources, 16O*
# 3(1)^- 6128.6
/gps/source/add 0.13275
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 6128.6 keV

# Gamma point sources, 16O*
# 0(2)^+ 6048.2
/gps/source/add 0.12655
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 6048.2 keV

# Gamma point sources, 16O*
# 1(1)^- 1067.5
/gps/source/add 0.00377
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 1067.5 keV

# Gamma point sources, 16O*
# 1(1)^- 986.9
/gps/source/add 0.04403
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 986.9 keV

# Gamma point sources, 16O*
# 2(1)^+ 867.7
/gps/source/add 0.01698
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 867.7 keV

# Gamma point sources, 16O*
# 2(1)^+ 787.2
/gps/source/add 0.00503
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/energy 787.2 keV

# Prints out a table when running
/gps/source/list




