./Gammasphere runMacroBatch1.mac
./Gammasphere runMacroBatch2.mac
./Gammasphere runMacroBatch3.mac
./Gammasphere runMacroBatch4.mac
./Gammasphere runMacroBatch5.mac
./Gammasphere runMacroBatch6.mac
./Gammasphere runMacroBatch7.mac
./Gammasphere runMacroBatch8.mac
./Gammasphere runMacroBatch9.mac
./Gammasphere runMacroBatch10.mac
./Gammasphere runMacroBatch11.mac
./Gammasphere runMacroBatch12.mac
./Gammasphere runMacroBatch13.mac
./Gammasphere runMacroBatch14.mac
./Gammasphere runMacroBatch15.mac
