# Gamma beam source
/gps/particle gamma
/gps/pos/type Beam

# the incident surface is in the y-z plane
#/gps/pos/rot1 0 1 0
#/gps/pos/rot2 0 0 1

# Shape of beam cross section
/gps/pos/shape Circle
/gps/pos/centre 0. 0. 0. cm
/gps/pos/radius 1. mm
/gps/pos/sigma_r 0.2 mm

# Travel along Z, 0.5 deg dispersion
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0
/gps/ang/type beam1d 
/gps/ang/sigma_r 0.5 deg

/gps/ene/mono 1500. keV
