# Germanium Gamma Spec Run Macro

# Setup
/control/saveHistory
#/run/numberOfThreads 1
/run/verbose 0

/run/initialize

# Hadronic options
/process/had/particle_hp/use_photo_evaporation true
/process/had/particle_hp/skip_missing_isotopes true
/process/had/particle_hp/neglect_Doppler_broadening true
/process/had/particle_hp/do_not_adjust_final_state true

#/process/em/deexcitation region true true true
#/process/em/fluo true
#/process/em/auger true
#/process/em/pixe true

/particle/createAllIon msc GenericIon
/particle/createAllIon ionIoni GenericIon
/particle/createAllIon CoulombScat GenericIon
/particle/createAllIon hIoni GenericIon
/particle/createAllIon photonNuclear GenericIon
/particle/createAllIon Decay GenericIon
/particle/createAllIon RadioactiveDecay GenericIon
/particle/createAllIon Rayl GenericIon


# General Particle Source
/control/execute gps_beam_200Hg.mac

# Shoot once
/run/beamOn 20